### ISSUE TITLE
question about safetynet

### ISSUE THREAD

**Issue by amiltonwong** [woven-planet/l5kit#372]
Hi, authors,

Is the code about safetynet released or not?

Thanks~

**Comment by blazejosinski** [comment]
Hello @amiltonwong,

Thank you for your interest in our work.

The SafetyNet paper is currently under review for a publication on a conference. If the paper gets accepted, we plan to release the reference implementation together with the camera-ready version of the manuscript.

**Comment by amiltonwong** [comment]
OK

**Comment by SAICEGR** [comment]
@blazejosinski 
Hi, is safetyNet released?  I could not find it in this repository

**Comment by blazejosinski** [comment]
Hi @SAICEGR,
unfortunately, the plan to release Safety Net was canceled. The additional work to separate the code from the production codebase is too big of an effort for now.
The updated version of the paper was presented this week at ICRA, and should be released on arxiv soon. It goes into the implementation in more detail, in order to compensate for the lack of source code.

**Comment by amiltonwong** [comment]
@blazejosinski ,

What's the paper title for the safetynet?

**Comment by SAICEGR** [comment]
@blazejosinski 
thanks for your response and look forward to your new achievement.

**Comment by PPPrior** [comment]
> 

Is the updated version of the paper presented or not?😳

**Comment by blazejosinski** [comment]
@amiltonwong the title is: "SafetyNet: Safe planning for real-world self-driving vehicles using machine-learned policies".
The old version is available at [arxiv](https://arxiv.org/abs/2109.13602).
The new one should be uploaded in near future. It will also be available in ICRA 2022 [proceedings](https://ieeexplore.ieee.org/xpl/conhome/1000639/all-proceedings), once they are published.
